"""
apps_controller/types.py

Dataclasses for APPS evaluation pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ProblemData:
    problem_id: str
    question: str
    starter_code: str = ""
    public_test_cases: Optional[Dict[str, List[str]]] = None
    all_test_cases: Optional[Dict[str, List[str]]] = None
    difficulty: Optional[str] = None
    url: Optional[str] = None
    raw: Dict[str, Any] = field(default_factory=dict)

    def best_eval_test_cases(self) -> Optional[Dict[str, List[str]]]:
        """
        Prefer official/all tests if present; otherwise fall back to public tests.
        """
        if self.all_test_cases and self.all_test_cases.get("inputs") and self.all_test_cases.get("outputs"):
            return self.all_test_cases
        if self.public_test_cases and self.public_test_cases.get("inputs") and self.public_test_cases.get("outputs"):
            return self.public_test_cases
        return None


@dataclass
class JudgeItem:
    qid: str
    verdict: str  # PASS / FAIL / PARTIAL / UNKNOWN
    reason: str = ""
    correction: str = ""


@dataclass
class Agent1Bundle:
    questions: List[Dict[str, str]]  # [{"qid": "...", "question": "..."}]
    gold_answers: List[Dict[str, str]]  # [{"qid": "...", "answer": "..."}]
    agent3_answers: List[Dict[str, str]]  # [{"qid": "...", "answer": "..."}]
    judge: List[JudgeItem]


@dataclass
class EvalCaseResult:
    status: str  # AC/WA/RE/TLE/FORBIDDEN/OK
    stdout: str
    stderr: str
    time_cost: float
    expected: Optional[str] = None
    input_data: Optional[str] = None


@dataclass
class EvalResult:
    passed: bool
    cases: List[EvalCaseResult]
    summary: Dict[str, Any] = field(default_factory=dict)


# apps_controller/types.py

from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class IterationState:
    # full question list used in current iteration
    question_template: List[Dict[str, str]] = field(default_factory=list)

    # previous round incorrect question ids (for next-round base)
    last_incorrect_qids: List[str] = field(default_factory=list)

    # evolving enhanced requirement text (becomes next-round base_requirement if tests fail)
    requirement_text: str = ""

    pending_mask_gap_blocks_text: str = ""

    # NEW: dynamic stop testcases generated by Agent2 (after round-1)
    dynamic_stop_test_cases: Dict[str, List[str]] = field(default_factory=lambda: {"inputs": [], "outputs": []})

    # NEW: fail streak for model-generated stop cases (keyed by a stable signature)
    dynamic_stop_streak: Dict[str, int] = field(default_factory=dict)
    pending_masked_text: str = ""